install:
  - rm -rf public || exit 0

script:
  - ./bin/hugo

deploy:
  provider: pages
  repo: jamesbvaughan/jamesbvaughan.github.io
  target-branch: master
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
