baseURL: https://jamesbvaughan.com/

languageCode: en-us

title: things james does

taxonomies:
  tag: tags

pygmentsCodefences: true

pygmentsUseClasses: true

pygmentsStyle: friendly

author:
  name: James Vaughan
  email: james@jamesbvaughan.com

params:
  gitRepo: https://github.com/jamesbvaughan/jamesbvaughan.com
  githubUsername: jamesbvaughan
  twitterHandle: jamesontheline

permalinks:
  posts: /:filename

outputFormats:
  RSS:
    baseName: feed
