baseURL: https://jamesbvaughan.com/

languageCode: en-us

title: things james does

author:
  name: James Vaughan
  email: james@jamesbvaughan.com

social:
  twitter: jamesontheline

disqusShortname: jamesbvaughan

params:
  gitRepo: https://github.com/jamesbvaughan/jamesbvaughan.com
  githubUsername: jamesbvaughan

outputFormats:
  RSS:
    baseName: feed

permalinks:
  posts: /:filename

taxonomies:
  series: series

pygmentsCodefences: true
pygmentsStyle: dracula
