baseURL: https://jamesbvaughan.com/

languageCode: en-us

title: james vaughan

disqusShortname: jamesbvaughan

params:
  gitRepo: https://github.com/jamesbvaughan/jamesbvaughan.com
  githubUsername: jamesbvaughan
  twitterHandle: jamesontheline
  author:
    name: James Vaughan
    email: james@jamesbvaughan.com

permalinks:
  posts: /:filename

enableRobotsTXT: true

disableKinds:
  - taxonomy

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: gruvbox
