baseURL: https://jamesbvaughan.com/

languageCode: en-us

title: things james does

author:
  name: James Vaughan
  email: james@jamesbvaughan.com

params:
  gitRepo: https://github.com/jamesbvaughan/jamesbvaughan.com
  githubUsername: jamesbvaughan
  twitterHandle: jamesontheline

taxonomies:
  tag: tags

outputFormats:
  RSS:
    baseName: feed

permalinks:
  posts: /:filename

pygmentsCodefences: true
pygmentsUseClasses: true
pygmentsStyle: friendly
