baseURL: https://jamesbvaughan.com/

languageCode: en-us

title: james vaughan

author:
  name: James Vaughan
  email: james@jamesbvaughan.com

disqusShortname: jamesbvaughan

params:
  gitRepo: https://github.com/jamesbvaughan/jamesbvaughan.com
  githubUsername: jamesbvaughan
  twitterHandle: jamesontheline

outputFormats:
  RSS:
    baseName: feed

permalinks:
  posts: /:filename

enableRobotsTXT: true

disableKinds:
- taxonomy
- taxonomyTerm

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: gruvbox
